config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Ilimetr API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('events/', include('events.urls')),
    path('interactive-elements/', include('interactive_elements.urls')),
    path('reports/', include('reports.urls')),
    path('meetings/', include('meetings.urls')),
    path('courses/', include('courses.urls')),
    path('notifications/', include('notifications.urls')),
    path('departments/', include('departments.urls')),
    path('api-courses/', include('courses.api_urls')),
    path('api-departments/', include('departments.api_urls')),
    path('api-interactive-elements/', include('interactive_elements.api_urls')),
    path('api-meetings/', include('meetings.api_urls')),
    path('api-notifications/', include('notifications.api_urls')),
    path('api-users/', include('users.api_urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

meetings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_meeting, name='create_meeting'),
    path('meeting/<int:meeting_id>/', views.meeting_detail, name='meeting_detail'),
    path('<int:meeting_id>/edit/', views.edit_meeting, name='edit_meeting'),
    path('my_meetings/', views.user_meetings, name='user_meetings'),
    path('calendar/', views.calendar_view, name='calendar'),
]

meetings/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from notifications.models import Notification


User = get_user_model()


class Meeting(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    url = models.URLField()
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='meetings_participants')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        participant_group, created = Group.objects.get_or_create(name='Participant')
        for participant in self.participants.all():
            participant.groups.add(participant_group)
            
    def __str__(self):
        return self.title


@receiver(m2m_changed, sender=Meeting.participants.through)
def participants_changed(sender, instance, action, pk_set, **kwargs):
    if action == "post_add":
        for user_id in pk_set:
            user = User.objects.get(pk=user_id)
            Notification.objects.create(
                user=user,
                message=f'You have been added to the meeting "{instance.title}" by {instance.host.username}.',
                link=instance.url
            )
            
    elif action == "post_remove":
        for user_id in pk_set:
            user = User.objects.get(pk=user_id)
            Notification.objects.create(
                user=user,
                message=f'You have been removed from the meeting "{instance.title}" by {instance.host.username}.'
            )

meetings/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Meeting
from django.core.exceptions import ValidationError
from django.utils import timezone

User = get_user_model()


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class MeetingForm(forms.ModelForm):
    participants = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    start_time = forms.DateTimeField(widget=DateTimeInput(attrs={'min': timezone.now().isoformat()}))
    end_time = forms.DateTimeField(widget=DateTimeInput(attrs={'min': timezone.now().isoformat()}))

    class Meta:
        model = Meeting
        fields = ['title', 'description', 'start_time', 'end_time', 'participants']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MeetingForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['participants'].queryset = User.objects.exclude(id=user.id)
            
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        if start_time and end_time:
            if start_time < timezone.now():
                self.add_error('start_time', "The start time cannot be in the past.")
            if end_time <= start_time:
                self.add_error('end_time', "The end time cannot be earlier (or equal) than the start time.")

        return cleaned_data

meetings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .models import Meeting
from .forms import MeetingForm
from notifications.models import Notification
from django.core.exceptions import PermissionDenied
from django.db import models
import requests


@login_required
def create_meeting(request):
    if request.method == 'POST':
        form = MeetingForm(request.POST, user=request.user)
        if form.is_valid():
            response = requests.post(
                'https://api.daily.co/v1/rooms',
                headers={
                    'Authorization': f'Bearer {settings.DAILY_CO_API_KEY}',
                    'Content-Type': 'application/json'
                },
                json={
                    'properties': {
                        'enable_chat': True,
                        'enable_screenshare': True,
                        'start_video_off': True,
                        'start_audio_off': True,
                        'enable_people_ui': True,
                        'enable_prejoin_ui': True,
                        'enable_network_ui': True,
                        'enable_emoji_reactions': True,
                        'enable_hand_raising': True,
                        'enable_knocking': True
                    }
                }
            )
            data = response.json()
            meeting_url = data['url']

            meeting = form.save(commit=False)
            meeting.url = meeting_url
            meeting.host = request.user
            meeting.save()
            form.save_m2m()

            return redirect('meeting_detail', meeting_id=meeting.id)
    else:
        form = MeetingForm()
    return render(request, 'meetings/create_meeting.html', {'form': form})


@login_required
def meeting_detail(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    return render(request, 'meetings/meeting_detail.html', {'meeting': meeting})


@login_required
def edit_meeting(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    if meeting.host != request.user:
        raise PermissionDenied

    if request.method == 'POST':
        form = MeetingForm(request.POST, instance=meeting, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('meeting_detail', meeting_id=meeting.id)
    else:
        form = MeetingForm(instance=meeting, user=request.user)
    return render(request, 'meetings/edit_meeting.html', {'form': form, 'meeting': meeting})


@login_required
def user_meetings(request):
    sort_by = request.GET.get('sort_by', 'start_time')
    order = request.GET.get('order', 'asc')
    
    if order == 'desc':
        sort_by = '-' + sort_by
    
    meetings = Meeting.objects.filter(host=request.user).order_by(sort_by)
    return render(request, 'meetings/user_meetings.html', {'meetings': meetings, 'sort_by': sort_by, 'order': order})


@login_required
def calendar_view(request):
    meetings_host = Meeting.objects.filter(models.Q(host=request.user))
    meetings_participant = Meeting.objects.filter(models.Q(participants=request.user))
    return render(request, 'meetings/calendar.html', {'meetings_host': meetings_host, 'meetings_participant': meetings_participant})

templates/meetings/calendar.html
{% extends 'base.html' %}

{% block extrahead %}
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.14/index.global.min.js'></script>
{% endblock %}

{% block content %}
    <h1>Meeting Calendar</h1>
    <h2>Host meets</h2>
    {% if meetings_host %}
        <ul>
        {% for meeting in meetings_host %}
            <li><a href="{% url 'meeting_detail' meeting.id %}">{{ meeting.title }}: {{ meeting.start_time }} - {{ meeting.end_time }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No host meeting</p>
    {% endif %}

    <h2>Participant meets</h2>
    {% if meetings_participant %}
        <ul>
        {% for meeting in meetings_participant %}
            <li><a href="{% url 'meeting_detail' meeting.id %}">{{ meeting.title }}: {{ meeting.start_time }} - {{ meeting.end_time }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Participant meeting</p>
    {% endif %}

    <div id='calendar'></div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'dayGridMonth',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
            eventDisplay: 'block',
            eventBackgroundColor: '#6e7fa7',
            eventBorderColor: '#6e7fa7',
            eventTextColor: '#fff',
            eventClick: function(info) {
                window.location.href = info.event.url;
            },
            events: [
                {% for meeting in meetings_host %}
                    {
                        title: '{{ meeting.title }}',
                        start: '{{ meeting.start_time|date:"Y-m-d\\TH:i:s" }}',
                        {% if meeting.end_time %}
                        end: '{{ meeting.end_time|date:"Y-m-d\\TH:i:s" }}',
                        {% endif %}
                        url: '{% url 'meeting_detail' meeting.id %}'
                    },
                {% endfor %}
                {% for meeting in meetings_participant %}
                    {
                        title: '{{ meeting.title }}',
                        start: '{{ meeting.start_time|date:"Y-m-d\\TH:i:s" }}',
                        {% if meeting.end_time %}
                        end: '{{ meeting.end_time|date:"Y-m-d\\TH:i:s" }}',
                        {% endif %}
                        url: '{% url 'meeting_detail' meeting.id %}'
                    },
                {% endfor %}
            ]
        });
        calendar.render();
    });
</script>

{% endblock %}

templates/meetings/create_meeting.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create Meeting</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Meeting</button>
    </form>
{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css">
    <script>
        $(function() {
            var dateFormat = "yy-mm-dd",
                from = $("#id_start_time")
                    .datetimepicker({
                        minDate: 0,
                        dateFormat: dateFormat
                    }),
                to = $("#id_end_time").datetimepicker({
                    minDate: 0,
                    dateFormat: dateFormat
                });
        });
    </script>
{% endblock %}

templates/meetings/edit_meeting.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit Meeting</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
</form>
{% endblock %}

{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css">
<script>
    $(function() {
        var dateFormat = "yy-mm-dd";
        $("#id_start_time").datetimepicker({
            minDate: 0,
            dateFormat: dateFormat,
            onClose: function(selectedDate) {
                $("#id_end_time").datetimepicker("option", "minDate", selectedDate);
            }
        });
        $("#id_end_time").datetimepicker({
            minDate: 0,
            dateFormat: dateFormat,
            onClose: function(selectedDate) {
                $("#id_start_time").datetimepicker("option", "maxDate", selectedDate);
            }
        });
    });
</script>
{% endblock %}

templates/meetings/meeting_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ meeting.title }}</h2>
<p>{{ meeting.description }}</p>
<p><a href="{{ meeting.url }}">Ссылка на встречу</a></p>
<p>Начало: {{ meeting.start_time }}</p>
<p>Окончание: {{ meeting.end_time }}</p>
<iframe src="{{ meeting.url }}" width="100%" height="700px" allow="camera; microphone; fullscreen"></iframe>
<a href="{% url 'user_meetings' %}">Back to meetings</a>
{% if meeting.host == request.user %}
    <a href="{% url 'edit_meeting' meeting_id=meeting.id %}">Изменить</a>
    <a href="{% url 'interactive_list' %}">Добавить Интерактив</a>
{% endif %}
{% endblock %}

templates/meetings/user_meetings.html
{% extends 'base.html' %}

{% block content %}
<h2>Мои встречи</h2>

<p>Сортировать по: 
    <a href="?sort_by=title&order={% if sort_by == 'title' and order == 'asc' %}desc{% else %}asc{% endif %}">Название</a> | 
    <a href="?sort_by=start_time&order={% if sort_by == 'start_time' and order == 'asc' %}desc{% else %}asc{% endif %}">Дата начала</a> | 
    <a href="?sort_by=end_time&order={% if sort_by == 'end_time' and order == 'asc' %}desc{% else %}asc{% endif %}">Дата окончания</a>
</p>

<ul>
    {% for meeting in meetings %}
        <li><a href="{% url 'meeting_detail' meeting_id=meeting.id %}">{{ meeting.title }}</a> - {{ meeting.start_time }}</li>
    {% endfor %}
</ul>

<a href="{% url 'create_meeting' %}">Создать новую встречу</a>
<a href="{% url 'interactive_list' %}">Добавить Интерактив</a>
{% endblock %}